### PR TITLE
Compatibility with which-key 3.x

### PR DESCRIPTION
**Pull request by Spiffyk**
This fixes `:checkhealth which-key` when using version >=3.0 of `which-key`.

### CODE REVIEW

**Comment by afreakk** [comment]
Thanks a lot, but now its no longer possible to have structured mappings ? 
like:
```
w = {
  x = { "something" }
}
```
Also this is a breaking change, `M.normal_mode` and `M.normal_and_visual_mode`  no longer exists, 
maybe mention that somewhere, or keep it compatible.

**Comment by dprophete** [comment]
> Thanks a lot, but now its no longer possible to have structured mappings ?
> like:
> 
> w = {
>   x = { "something" }
> }

The convention is now to fully spell out the mapping, so it would be 
```
{ "wx", "something", desc = ... }
```

**Comment by dprophete** [comment]
> Also this is a breaking change, M.normal_mode and M.normal_and_visual_mode no longer exists,
maybe mention that somewhere, or keep it compatible.

I would assume this was only used in the 'old' setup like:
```
		config = function()
			local wk = require("which-key")
			local uwk = require("unimpaired-which-key")
			wk.register(uwk.normal_mode)
			wk.register(uwk.normal_and_visual_mode, { mode = { "n", "v" } })
		end,
```

but these are not needed anymore... Maybe just set them up as `{}` ?

**Comment by Spiffyk** [comment]
As @dprophete says, the structure has changed. `which-key` still *does* accept the old version via `register()`, but `add()` is preferred and the health check keeps nagging if we do it the old way. 

It is true that this update is breaking and requires user intervention to come through, but I'm not really sure how to keep it compatible with the old version, short of practically duplicating the code, or generating the old structure alongside the new one.

Maybe the best course of action would be to just keep the old and new versions of `unimpaired-which-key` in separate repos, or at least branches, which would then be manually switchable in plugin managers? If that is preferred, I can keep this new version under my namespace and maintain it, or you, @afreakk, do feel free to take my changes and put them in your own repo.

**Comment by eliasnorrby** [comment]
> Maybe the best course of action would be to just keep the old and new versions of `unimpaired-which-key` in separate repos, or at least branches, which would then be manually switchable in plugin managers? If that is preferred, I can keep this new version under my namespace and maintain it, or you, @afreakk, do feel free to take my changes and put them in your own repo.

How about merging this and just publishing a new release? Most plugin managers allow pinning a plugin to a certain tag or even commit – this plugin has a `v0.1` tag that could serve as a compatibility mode for anybody who's still using `which-key` v2.

I'd suggest adding a section to the readme along the lines of:

```md
# Compatibility with `which-key` v2.x

This plugin has been updated to leverage the new APIs added in `which-key` v3. For compatibility with older versions of `which-key`, pin this plugin to the `v0.1` tag.
```

I feel like this is a pretty common approach, although I can't think of any examples off the top of my head.

**Comment by afreakk** [comment]
> > Maybe the best course of action would be to just keep the old and new versions of `unimpaired-which-key` in separate repos, or at least branches, which would then be manually switchable in plugin managers? If that is preferred, I can keep this new version under my namespace and maintain it, or you, @afreakk, do feel free to take my changes and put them in your own repo.
> 
> How about merging this and just publishing a new release? Most plugin managers allow pinning a plugin to a certain tag or even commit – this plugin has a `v0.1` tag that could serve as a compatibility mode for anybody who's still using `which-key` v2.
> 
> I'd suggest adding a section to the readme along the lines of:
> 
> ```
> # Compatibility with `which-key` v2.x
> 
> This plugin has been updated to leverage the new APIs added in `which-key` v3. For compatibility with older versions of `which-key`, pin this plugin to the `v0.1` tag.
> ```
> 
> I feel like this is a pretty common approach, although I can't think of any examples off the top of my head.

yeah good idea

**Comment by afreakk** [comment]
I tried this just now on my computer, and it seems most work.
But the mappings that start with 'yo' didnt seem to work for me.
Does it work for you guys?

**Comment by afreakk** [comment]
it seems, its related to this https://github.com/folke/which-key.nvim/issues/672

If I add 
```
            triggers = {
                { "<auto>", mode = "nixsotc" },
                { "y",      mode = { "n" } },
            }
```
I get unimpaired `yo` binding shown in which-key, but then I loose all operator pending bindings that normally show after pressing `y`...
So not sure if its possible to get both unimpaired (`yo`) and operator pending mappings shown at the same time.
because of changes in v3

**Pull request merged**
